const express = require("express")
const app = express()
const cookieparser = require("cookie-parser")
app.use(cookieparser())
app.use(express.json())
const Database = require("./Connection/database")
const Hotel = require("./Route/Hotel")
const Auth = require("./Route/Auth")
const User = require("./Route/User")
const Room = require("./Route/Room")
Database.connect()
app.use('/hotel', Hotel, Auth, User, Room)
app.listen(9000)
console.log("We are running on http://localhost:9000")
module.exports = app